In [3]:
import numpy as np
import torch
from torch import Tensor



In [24]:
torch.manual_seed(42)

a = torch.randn(3,2)
a_pre = a.storage();
a_t = a.T
print(f"{a.storage()}")
torch.testing.assert_close(a_t.storage(), a.storage())
# torch.testing.assert_close(a_t.stride(), a.stride())
print(f"{a} and \n {a_t}")
print(f"{a.stride()} and {a_t.stride()}")
b = Tensor.contiguous(a_t)
print(f"{b}, \n {b.shape} \n {b.stride()}")
print(f"{b.storage()}")
print(f"{a.is_contiguous()} {a_t.is_contiguous()} {b.is_contiguous()}")

 0.33669036626815796
 0.12880940735340118
 0.23446236550807953
 0.23033303022384644
 -1.1228563785552979
 -0.18632829189300537
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
tensor([[ 0.3367,  0.1288],
        [ 0.2345,  0.2303],
        [-1.1229, -0.1863]]) and 
 tensor([[ 0.3367,  0.2345, -1.1229],
        [ 0.1288,  0.2303, -0.1863]])
(2, 1) and (1, 2)
tensor([[ 0.3367,  0.2345, -1.1229],
        [ 0.1288,  0.2303, -0.1863]]), 
 torch.Size([2, 3]) 
 (3, 1)
 0.33669036626815796
 0.23446236550807953
 -1.1228563785552979
 0.12880940735340118
 0.23033303022384644
 -0.18632829189300537
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
True False True


In [41]:
#Chunking!!
'''
Say if you create a new tensor with just the row of a[1] which is a 3x2 tensor, 
then the new tensor b will actually still be pointing to the a's memory but just with an offset!
'''
torch.manual_seed(42)
a = torch.randn((4,3,2))
b = a[1]
print(f"{a.shape} {b.shape}")
print(f"{a.storage_offset()} {b.storage_offset()}")
for (a_s, b_s) in zip(a.storage(), b.storage()):
    if(a_s != b_s):
        print("Wrong!")

torch.Size([4, 3, 2]) torch.Size([3, 2])
0 6
